apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/moodledata && chmod 777 /var/moodledata"]
          volumeMounts:
            - name: moodledata-storage
              mountPath: /var/moodledata
      containers:
        - name: moodle
          image: jiaying0811/esm-moodle:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APACHE_DOCUMENT_ROOT
              value: /var/www/html/public
            - name: MOODLE_DB_HOST
              value: moodle-mariadb
            - name: MOODLE_DB_NAME
              value: moodle
            - name: MOODLE_DB_USER
              value: moodleuser
            - name: MOODLE_DB_PASSWORD
              value: moodlepass
            - name: MOODLE_WWWROOT
              value: http://staging-moodle.85.211.209.146.nip.io
          volumeMounts:
            - name: moodledata-storage
              mountPath: /var/moodledata
      volumes:
        - name: moodledata-storage
          persistentVolumeClaim:
            claimName: moodle-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: moodle
  ports:
    - port: 80
      targetPort: 80
